# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app.bridges.artifacts.protos.billing_api_pb2 as billing__api__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in billing_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BillingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllPlans = channel.unary_unary(
                '/billing_api.BillingService/GetAllPlans',
                request_serializer=billing__api__pb2.GetAllPlansRequest.SerializeToString,
                response_deserializer=billing__api__pb2.GetAllPlansResponse.FromString,
                _registered_method=True)
        self.GetSubscription = channel.unary_unary(
                '/billing_api.BillingService/GetSubscription',
                request_serializer=billing__api__pb2.GetSubscriptionRequest.SerializeToString,
                response_deserializer=billing__api__pb2.GetSubscriptionResponse.FromString,
                _registered_method=True)
        self.UpdateSubscription = channel.unary_unary(
                '/billing_api.BillingService/UpdateSubscription',
                request_serializer=billing__api__pb2.UpdateSubscriptionRequest.SerializeToString,
                response_deserializer=billing__api__pb2.UpdateSubscriptionResponse.FromString,
                _registered_method=True)


class BillingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllPlans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubscription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSubscription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllPlans': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllPlans,
                    request_deserializer=billing__api__pb2.GetAllPlansRequest.FromString,
                    response_serializer=billing__api__pb2.GetAllPlansResponse.SerializeToString,
            ),
            'GetSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubscription,
                    request_deserializer=billing__api__pb2.GetSubscriptionRequest.FromString,
                    response_serializer=billing__api__pb2.GetSubscriptionResponse.SerializeToString,
            ),
            'UpdateSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSubscription,
                    request_deserializer=billing__api__pb2.UpdateSubscriptionRequest.FromString,
                    response_serializer=billing__api__pb2.UpdateSubscriptionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'billing_api.BillingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('billing_api.BillingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BillingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllPlans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/billing_api.BillingService/GetAllPlans',
            billing__api__pb2.GetAllPlansRequest.SerializeToString,
            billing__api__pb2.GetAllPlansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/billing_api.BillingService/GetSubscription',
            billing__api__pb2.GetSubscriptionRequest.SerializeToString,
            billing__api__pb2.GetSubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/billing_api.BillingService/UpdateSubscription',
            billing__api__pb2.UpdateSubscriptionRequest.SerializeToString,
            billing__api__pb2.UpdateSubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
