// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: agentkit.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AgentKit_Talk_FullMethodName = "/talk_api.AgentKit/Talk"
)

// AgentKitClient is the client API for AgentKit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentKitClient interface {
	// Bi-directional streaming RPC for agent communication
	Talk(ctx context.Context, opts ...grpc.CallOption) (AgentKit_TalkClient, error)
}

type agentKitClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentKitClient(cc grpc.ClientConnInterface) AgentKitClient {
	return &agentKitClient{cc}
}

func (c *agentKitClient) Talk(ctx context.Context, opts ...grpc.CallOption) (AgentKit_TalkClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentKit_ServiceDesc.Streams[0], AgentKit_Talk_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentKitTalkClient{stream}
	return x, nil
}

type AgentKit_TalkClient interface {
	Send(*TalkInput) error
	Recv() (*TalkOutput, error)
	grpc.ClientStream
}

type agentKitTalkClient struct {
	grpc.ClientStream
}

func (x *agentKitTalkClient) Send(m *TalkInput) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentKitTalkClient) Recv() (*TalkOutput, error) {
	m := new(TalkOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentKitServer is the server API for AgentKit service.
// All implementations should embed UnimplementedAgentKitServer
// for forward compatibility
type AgentKitServer interface {
	// Bi-directional streaming RPC for agent communication
	Talk(AgentKit_TalkServer) error
}

// UnimplementedAgentKitServer should be embedded to have forward compatible implementations.
type UnimplementedAgentKitServer struct {
}

func (UnimplementedAgentKitServer) Talk(AgentKit_TalkServer) error {
	return status.Errorf(codes.Unimplemented, "method Talk not implemented")
}

// UnsafeAgentKitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentKitServer will
// result in compilation errors.
type UnsafeAgentKitServer interface {
	mustEmbedUnimplementedAgentKitServer()
}

func RegisterAgentKitServer(s grpc.ServiceRegistrar, srv AgentKitServer) {
	s.RegisterService(&AgentKit_ServiceDesc, srv)
}

func _AgentKit_Talk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentKitServer).Talk(&agentKitTalkServer{stream})
}

type AgentKit_TalkServer interface {
	Send(*TalkOutput) error
	Recv() (*TalkInput, error)
	grpc.ServerStream
}

type agentKitTalkServer struct {
	grpc.ServerStream
}

func (x *agentKitTalkServer) Send(m *TalkOutput) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentKitTalkServer) Recv() (*TalkInput, error) {
	m := new(TalkInput)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentKit_ServiceDesc is the grpc.ServiceDesc for AgentKit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentKit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "talk_api.AgentKit",
	HandlerType: (*AgentKitServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Talk",
			Handler:       _AgentKit_Talk_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agentkit.proto",
}
