// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: integration-api.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UnifiedProviderService_Chat_FullMethodName             = "/integration_api.UnifiedProviderService/Chat"
	UnifiedProviderService_StreamChat_FullMethodName       = "/integration_api.UnifiedProviderService/StreamChat"
	UnifiedProviderService_Embedding_FullMethodName        = "/integration_api.UnifiedProviderService/Embedding"
	UnifiedProviderService_Reranking_FullMethodName        = "/integration_api.UnifiedProviderService/Reranking"
	UnifiedProviderService_VerifyCredential_FullMethodName = "/integration_api.UnifiedProviderService/VerifyCredential"
)

// UnifiedProviderServiceClient is the client API for UnifiedProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UnifiedProviderServiceClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	StreamChat(ctx context.Context, opts ...grpc.CallOption) (UnifiedProviderService_StreamChatClient, error)
	Embedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
	Reranking(ctx context.Context, in *RerankingRequest, opts ...grpc.CallOption) (*RerankingResponse, error)
	VerifyCredential(ctx context.Context, in *VerifyCredentialRequest, opts ...grpc.CallOption) (*VerifyCredentialResponse, error)
}

type unifiedProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUnifiedProviderServiceClient(cc grpc.ClientConnInterface) UnifiedProviderServiceClient {
	return &unifiedProviderServiceClient{cc}
}

func (c *unifiedProviderServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, UnifiedProviderService_Chat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifiedProviderServiceClient) StreamChat(ctx context.Context, opts ...grpc.CallOption) (UnifiedProviderService_StreamChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &UnifiedProviderService_ServiceDesc.Streams[0], UnifiedProviderService_StreamChat_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &unifiedProviderServiceStreamChatClient{stream}
	return x, nil
}

type UnifiedProviderService_StreamChatClient interface {
	Send(*ChatRequest) error
	Recv() (*ChatResponse, error)
	grpc.ClientStream
}

type unifiedProviderServiceStreamChatClient struct {
	grpc.ClientStream
}

func (x *unifiedProviderServiceStreamChatClient) Send(m *ChatRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *unifiedProviderServiceStreamChatClient) Recv() (*ChatResponse, error) {
	m := new(ChatResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *unifiedProviderServiceClient) Embedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, UnifiedProviderService_Embedding_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifiedProviderServiceClient) Reranking(ctx context.Context, in *RerankingRequest, opts ...grpc.CallOption) (*RerankingResponse, error) {
	out := new(RerankingResponse)
	err := c.cc.Invoke(ctx, UnifiedProviderService_Reranking_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifiedProviderServiceClient) VerifyCredential(ctx context.Context, in *VerifyCredentialRequest, opts ...grpc.CallOption) (*VerifyCredentialResponse, error) {
	out := new(VerifyCredentialResponse)
	err := c.cc.Invoke(ctx, UnifiedProviderService_VerifyCredential_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnifiedProviderServiceServer is the server API for UnifiedProviderService service.
// All implementations should embed UnimplementedUnifiedProviderServiceServer
// for forward compatibility
type UnifiedProviderServiceServer interface {
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	StreamChat(UnifiedProviderService_StreamChatServer) error
	Embedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error)
	Reranking(context.Context, *RerankingRequest) (*RerankingResponse, error)
	VerifyCredential(context.Context, *VerifyCredentialRequest) (*VerifyCredentialResponse, error)
}

// UnimplementedUnifiedProviderServiceServer should be embedded to have forward compatible implementations.
type UnimplementedUnifiedProviderServiceServer struct {
}

func (UnimplementedUnifiedProviderServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedUnifiedProviderServiceServer) StreamChat(UnifiedProviderService_StreamChatServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamChat not implemented")
}
func (UnimplementedUnifiedProviderServiceServer) Embedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Embedding not implemented")
}
func (UnimplementedUnifiedProviderServiceServer) Reranking(context.Context, *RerankingRequest) (*RerankingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reranking not implemented")
}
func (UnimplementedUnifiedProviderServiceServer) VerifyCredential(context.Context, *VerifyCredentialRequest) (*VerifyCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyCredential not implemented")
}

// UnsafeUnifiedProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UnifiedProviderServiceServer will
// result in compilation errors.
type UnsafeUnifiedProviderServiceServer interface {
	mustEmbedUnimplementedUnifiedProviderServiceServer()
}

func RegisterUnifiedProviderServiceServer(s grpc.ServiceRegistrar, srv UnifiedProviderServiceServer) {
	s.RegisterService(&UnifiedProviderService_ServiceDesc, srv)
}

func _UnifiedProviderService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifiedProviderServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnifiedProviderService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifiedProviderServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnifiedProviderService_StreamChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UnifiedProviderServiceServer).StreamChat(&unifiedProviderServiceStreamChatServer{stream})
}

type UnifiedProviderService_StreamChatServer interface {
	Send(*ChatResponse) error
	Recv() (*ChatRequest, error)
	grpc.ServerStream
}

type unifiedProviderServiceStreamChatServer struct {
	grpc.ServerStream
}

func (x *unifiedProviderServiceStreamChatServer) Send(m *ChatResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *unifiedProviderServiceStreamChatServer) Recv() (*ChatRequest, error) {
	m := new(ChatRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _UnifiedProviderService_Embedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifiedProviderServiceServer).Embedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnifiedProviderService_Embedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifiedProviderServiceServer).Embedding(ctx, req.(*EmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnifiedProviderService_Reranking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RerankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifiedProviderServiceServer).Reranking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnifiedProviderService_Reranking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifiedProviderServiceServer).Reranking(ctx, req.(*RerankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnifiedProviderService_VerifyCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifiedProviderServiceServer).VerifyCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnifiedProviderService_VerifyCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifiedProviderServiceServer).VerifyCredential(ctx, req.(*VerifyCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UnifiedProviderService_ServiceDesc is the grpc.ServiceDesc for UnifiedProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UnifiedProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "integration_api.UnifiedProviderService",
	HandlerType: (*UnifiedProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _UnifiedProviderService_Chat_Handler,
		},
		{
			MethodName: "Embedding",
			Handler:    _UnifiedProviderService_Embedding_Handler,
		},
		{
			MethodName: "Reranking",
			Handler:    _UnifiedProviderService_Reranking_Handler,
		},
		{
			MethodName: "VerifyCredential",
			Handler:    _UnifiedProviderService_VerifyCredential_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChat",
			Handler:       _UnifiedProviderService_StreamChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "integration-api.proto",
}
