// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: talk-api.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TalkService_AssistantTalk_FullMethodName               = "/talk_api.TalkService/AssistantTalk"
	TalkService_GetAllAssistantConversation_FullMethodName = "/talk_api.TalkService/GetAllAssistantConversation"
	TalkService_GetAllConversationMessage_FullMethodName   = "/talk_api.TalkService/GetAllConversationMessage"
	TalkService_CreateMessageMetric_FullMethodName         = "/talk_api.TalkService/CreateMessageMetric"
	TalkService_CreateConversationMetric_FullMethodName    = "/talk_api.TalkService/CreateConversationMetric"
	TalkService_CreatePhoneCall_FullMethodName             = "/talk_api.TalkService/CreatePhoneCall"
	TalkService_CreateBulkPhoneCall_FullMethodName         = "/talk_api.TalkService/CreateBulkPhoneCall"
)

// TalkServiceClient is the client API for TalkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TalkServiceClient interface {
	// Bi-directional streaming RPC for assistant messaging
	AssistantTalk(ctx context.Context, opts ...grpc.CallOption) (TalkService_AssistantTalkClient, error)
	// Get all assistant conversations
	GetAllAssistantConversation(ctx context.Context, in *GetAllAssistantConversationRequest, opts ...grpc.CallOption) (*GetAllAssistantConversationResponse, error)
	// Get all messages in a conversation
	GetAllConversationMessage(ctx context.Context, in *GetAllConversationMessageRequest, opts ...grpc.CallOption) (*GetAllConversationMessageResponse, error)
	// Create message metric
	CreateMessageMetric(ctx context.Context, in *CreateMessageMetricRequest, opts ...grpc.CallOption) (*CreateMessageMetricResponse, error)
	// Create conversation metric
	CreateConversationMetric(ctx context.Context, in *CreateConversationMetricRequest, opts ...grpc.CallOption) (*CreateConversationMetricResponse, error)
	// Create phone call
	CreatePhoneCall(ctx context.Context, in *CreatePhoneCallRequest, opts ...grpc.CallOption) (*CreatePhoneCallResponse, error)
	// Create bulk phone calls
	CreateBulkPhoneCall(ctx context.Context, in *CreateBulkPhoneCallRequest, opts ...grpc.CallOption) (*CreateBulkPhoneCallResponse, error)
}

type talkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTalkServiceClient(cc grpc.ClientConnInterface) TalkServiceClient {
	return &talkServiceClient{cc}
}

func (c *talkServiceClient) AssistantTalk(ctx context.Context, opts ...grpc.CallOption) (TalkService_AssistantTalkClient, error) {
	stream, err := c.cc.NewStream(ctx, &TalkService_ServiceDesc.Streams[0], TalkService_AssistantTalk_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &talkServiceAssistantTalkClient{stream}
	return x, nil
}

type TalkService_AssistantTalkClient interface {
	Send(*AssistantTalkRequest) error
	Recv() (*AssistantTalkResponse, error)
	grpc.ClientStream
}

type talkServiceAssistantTalkClient struct {
	grpc.ClientStream
}

func (x *talkServiceAssistantTalkClient) Send(m *AssistantTalkRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *talkServiceAssistantTalkClient) Recv() (*AssistantTalkResponse, error) {
	m := new(AssistantTalkResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *talkServiceClient) GetAllAssistantConversation(ctx context.Context, in *GetAllAssistantConversationRequest, opts ...grpc.CallOption) (*GetAllAssistantConversationResponse, error) {
	out := new(GetAllAssistantConversationResponse)
	err := c.cc.Invoke(ctx, TalkService_GetAllAssistantConversation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talkServiceClient) GetAllConversationMessage(ctx context.Context, in *GetAllConversationMessageRequest, opts ...grpc.CallOption) (*GetAllConversationMessageResponse, error) {
	out := new(GetAllConversationMessageResponse)
	err := c.cc.Invoke(ctx, TalkService_GetAllConversationMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talkServiceClient) CreateMessageMetric(ctx context.Context, in *CreateMessageMetricRequest, opts ...grpc.CallOption) (*CreateMessageMetricResponse, error) {
	out := new(CreateMessageMetricResponse)
	err := c.cc.Invoke(ctx, TalkService_CreateMessageMetric_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talkServiceClient) CreateConversationMetric(ctx context.Context, in *CreateConversationMetricRequest, opts ...grpc.CallOption) (*CreateConversationMetricResponse, error) {
	out := new(CreateConversationMetricResponse)
	err := c.cc.Invoke(ctx, TalkService_CreateConversationMetric_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talkServiceClient) CreatePhoneCall(ctx context.Context, in *CreatePhoneCallRequest, opts ...grpc.CallOption) (*CreatePhoneCallResponse, error) {
	out := new(CreatePhoneCallResponse)
	err := c.cc.Invoke(ctx, TalkService_CreatePhoneCall_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talkServiceClient) CreateBulkPhoneCall(ctx context.Context, in *CreateBulkPhoneCallRequest, opts ...grpc.CallOption) (*CreateBulkPhoneCallResponse, error) {
	out := new(CreateBulkPhoneCallResponse)
	err := c.cc.Invoke(ctx, TalkService_CreateBulkPhoneCall_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TalkServiceServer is the server API for TalkService service.
// All implementations should embed UnimplementedTalkServiceServer
// for forward compatibility
type TalkServiceServer interface {
	// Bi-directional streaming RPC for assistant messaging
	AssistantTalk(TalkService_AssistantTalkServer) error
	// Get all assistant conversations
	GetAllAssistantConversation(context.Context, *GetAllAssistantConversationRequest) (*GetAllAssistantConversationResponse, error)
	// Get all messages in a conversation
	GetAllConversationMessage(context.Context, *GetAllConversationMessageRequest) (*GetAllConversationMessageResponse, error)
	// Create message metric
	CreateMessageMetric(context.Context, *CreateMessageMetricRequest) (*CreateMessageMetricResponse, error)
	// Create conversation metric
	CreateConversationMetric(context.Context, *CreateConversationMetricRequest) (*CreateConversationMetricResponse, error)
	// Create phone call
	CreatePhoneCall(context.Context, *CreatePhoneCallRequest) (*CreatePhoneCallResponse, error)
	// Create bulk phone calls
	CreateBulkPhoneCall(context.Context, *CreateBulkPhoneCallRequest) (*CreateBulkPhoneCallResponse, error)
}

// UnimplementedTalkServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTalkServiceServer struct {
}

func (UnimplementedTalkServiceServer) AssistantTalk(TalkService_AssistantTalkServer) error {
	return status.Errorf(codes.Unimplemented, "method AssistantTalk not implemented")
}
func (UnimplementedTalkServiceServer) GetAllAssistantConversation(context.Context, *GetAllAssistantConversationRequest) (*GetAllAssistantConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllAssistantConversation not implemented")
}
func (UnimplementedTalkServiceServer) GetAllConversationMessage(context.Context, *GetAllConversationMessageRequest) (*GetAllConversationMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllConversationMessage not implemented")
}
func (UnimplementedTalkServiceServer) CreateMessageMetric(context.Context, *CreateMessageMetricRequest) (*CreateMessageMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMessageMetric not implemented")
}
func (UnimplementedTalkServiceServer) CreateConversationMetric(context.Context, *CreateConversationMetricRequest) (*CreateConversationMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConversationMetric not implemented")
}
func (UnimplementedTalkServiceServer) CreatePhoneCall(context.Context, *CreatePhoneCallRequest) (*CreatePhoneCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePhoneCall not implemented")
}
func (UnimplementedTalkServiceServer) CreateBulkPhoneCall(context.Context, *CreateBulkPhoneCallRequest) (*CreateBulkPhoneCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBulkPhoneCall not implemented")
}

// UnsafeTalkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TalkServiceServer will
// result in compilation errors.
type UnsafeTalkServiceServer interface {
	mustEmbedUnimplementedTalkServiceServer()
}

func RegisterTalkServiceServer(s grpc.ServiceRegistrar, srv TalkServiceServer) {
	s.RegisterService(&TalkService_ServiceDesc, srv)
}

func _TalkService_AssistantTalk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TalkServiceServer).AssistantTalk(&talkServiceAssistantTalkServer{stream})
}

type TalkService_AssistantTalkServer interface {
	Send(*AssistantTalkResponse) error
	Recv() (*AssistantTalkRequest, error)
	grpc.ServerStream
}

type talkServiceAssistantTalkServer struct {
	grpc.ServerStream
}

func (x *talkServiceAssistantTalkServer) Send(m *AssistantTalkResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *talkServiceAssistantTalkServer) Recv() (*AssistantTalkRequest, error) {
	m := new(AssistantTalkRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TalkService_GetAllAssistantConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllAssistantConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalkServiceServer).GetAllAssistantConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalkService_GetAllAssistantConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalkServiceServer).GetAllAssistantConversation(ctx, req.(*GetAllAssistantConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalkService_GetAllConversationMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllConversationMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalkServiceServer).GetAllConversationMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalkService_GetAllConversationMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalkServiceServer).GetAllConversationMessage(ctx, req.(*GetAllConversationMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalkService_CreateMessageMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalkServiceServer).CreateMessageMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalkService_CreateMessageMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalkServiceServer).CreateMessageMetric(ctx, req.(*CreateMessageMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalkService_CreateConversationMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConversationMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalkServiceServer).CreateConversationMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalkService_CreateConversationMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalkServiceServer).CreateConversationMetric(ctx, req.(*CreateConversationMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalkService_CreatePhoneCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePhoneCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalkServiceServer).CreatePhoneCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalkService_CreatePhoneCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalkServiceServer).CreatePhoneCall(ctx, req.(*CreatePhoneCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalkService_CreateBulkPhoneCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBulkPhoneCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalkServiceServer).CreateBulkPhoneCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalkService_CreateBulkPhoneCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalkServiceServer).CreateBulkPhoneCall(ctx, req.(*CreateBulkPhoneCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TalkService_ServiceDesc is the grpc.ServiceDesc for TalkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TalkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "talk_api.TalkService",
	HandlerType: (*TalkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllAssistantConversation",
			Handler:    _TalkService_GetAllAssistantConversation_Handler,
		},
		{
			MethodName: "GetAllConversationMessage",
			Handler:    _TalkService_GetAllConversationMessage_Handler,
		},
		{
			MethodName: "CreateMessageMetric",
			Handler:    _TalkService_CreateMessageMetric_Handler,
		},
		{
			MethodName: "CreateConversationMetric",
			Handler:    _TalkService_CreateConversationMetric_Handler,
		},
		{
			MethodName: "CreatePhoneCall",
			Handler:    _TalkService_CreatePhoneCall_Handler,
		},
		{
			MethodName: "CreateBulkPhoneCall",
			Handler:    _TalkService_CreateBulkPhoneCall_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AssistantTalk",
			Handler:       _TalkService_AssistantTalk_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "talk-api.proto",
}
