// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: webrtc.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WebRTC_WebTalk_FullMethodName = "/talk_api.WebRTC/WebTalk"
)

// WebRTCClient is the client API for WebRTC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebRTCClient interface {
	// Bi-directional streaming RPC for WebRTC-based conversation
	WebTalk(ctx context.Context, opts ...grpc.CallOption) (WebRTC_WebTalkClient, error)
}

type webRTCClient struct {
	cc grpc.ClientConnInterface
}

func NewWebRTCClient(cc grpc.ClientConnInterface) WebRTCClient {
	return &webRTCClient{cc}
}

func (c *webRTCClient) WebTalk(ctx context.Context, opts ...grpc.CallOption) (WebRTC_WebTalkClient, error) {
	stream, err := c.cc.NewStream(ctx, &WebRTC_ServiceDesc.Streams[0], WebRTC_WebTalk_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &webRTCWebTalkClient{stream}
	return x, nil
}

type WebRTC_WebTalkClient interface {
	Send(*WebTalkRequest) error
	Recv() (*WebTalkResponse, error)
	grpc.ClientStream
}

type webRTCWebTalkClient struct {
	grpc.ClientStream
}

func (x *webRTCWebTalkClient) Send(m *WebTalkRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *webRTCWebTalkClient) Recv() (*WebTalkResponse, error) {
	m := new(WebTalkResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WebRTCServer is the server API for WebRTC service.
// All implementations should embed UnimplementedWebRTCServer
// for forward compatibility
type WebRTCServer interface {
	// Bi-directional streaming RPC for WebRTC-based conversation
	WebTalk(WebRTC_WebTalkServer) error
}

// UnimplementedWebRTCServer should be embedded to have forward compatible implementations.
type UnimplementedWebRTCServer struct {
}

func (UnimplementedWebRTCServer) WebTalk(WebRTC_WebTalkServer) error {
	return status.Errorf(codes.Unimplemented, "method WebTalk not implemented")
}

// UnsafeWebRTCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebRTCServer will
// result in compilation errors.
type UnsafeWebRTCServer interface {
	mustEmbedUnimplementedWebRTCServer()
}

func RegisterWebRTCServer(s grpc.ServiceRegistrar, srv WebRTCServer) {
	s.RegisterService(&WebRTC_ServiceDesc, srv)
}

func _WebRTC_WebTalk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WebRTCServer).WebTalk(&webRTCWebTalkServer{stream})
}

type WebRTC_WebTalkServer interface {
	Send(*WebTalkResponse) error
	Recv() (*WebTalkRequest, error)
	grpc.ServerStream
}

type webRTCWebTalkServer struct {
	grpc.ServerStream
}

func (x *webRTCWebTalkServer) Send(m *WebTalkResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *webRTCWebTalkServer) Recv() (*WebTalkRequest, error) {
	m := new(WebTalkRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WebRTC_ServiceDesc is the grpc.ServiceDesc for WebRTC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebRTC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "talk_api.WebRTC",
	HandlerType: (*WebRTCServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WebTalk",
			Handler:       _WebRTC_WebTalk_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "webrtc.proto",
}
